# Site settings
title: An Panc Patisserie
email: helenohagan55@gmail.com
description: Creative Cakes & Quirky Bakes
baseurl: ""
url: "http://anpanc.github.io/"

# User setting
owner: Helen O'Hagan
email: helenohagan55@gmail.com
facebook_username: AnPancPatisserie
twitter_username: pabens
github_username: anpanc
address:
  - line: Gortahork
  - line: Donegal
  - line: Ireland
telephone: +353 (87) 398 9812
copyright: Helen O'Hagan

# Google Maps API
google_api_key: AIzaSyAzghuPk263vISYYxSL7z_P38C0LkYxCd0

# Google Analytics
google_tracking_id: UA-78122891-1

# Build settings
markdown: kramdown

# exclude vendor for travis
exclude: [vendor]

# gems - for sitemap
gems:
  - jekyll-sitemap
  
