- name: Sweet Treats
  description: Be tempted by our selection of freshly baked cakes, tarts and tray bakes.
  icon: fa-cutlery

- name: Tea &amp; Coffee
  description: Enjoy a Nespresso Coffee or try one of our Suki Teas.
  icon: fa-coffee

- name: Local
  description: We use local suppliers and locally foraged seasonal ingredients whenever possible.
  icon: fa-leaf

- name: Special Events
  description: Birthdays, parties or just Sunday dinner; our outside catering menu suits every occasion.
  icon: fa-birthday-cake
